---
- name: Prevent the role from running without a properly configured dkim_domains array 1 of 2
  assert:
    that:
      - dkim_domains is iterable
      - dkim_domains is not string
      - (dkim_domains | length) > 0
    msg: Your dkim_domains list is invalid. Please review the dkim role's readme for required variables.

- name: Prevent the role from running without a properly configured dkim_domains array 2 of 2
  assert:
    that:
      - item.name is defined
      - item.name != ''
      - item.selector is defined
      - item.selector != ''
      - item.signing_table_pattern is defined
      - item.signing_table_pattern != ''
    msg: Your dkim_domains list is invalid. Please review the dkim role's readme for required variables.
  loop: "{{ dkim_domains }}"

- include_vars: "vars/{{ ansible_os_family }}.yml"

- include: opendkim.yml

- include: postfix.yml
