---
- name: opendkim packages are installed (debian-ish)
  apt:
    pkg:
      - opendkim
      - opendkim-tools
    state: present
  when: ansible_os_family == 'Debian'

- name: opendkim packages are installed (redhat-ish)
  yum:
    name:
      - opendkim
    state: present
  when: ansible_os_family == 'RedHat'

- name: opendkim socket configured
  lineinfile: dest=/etc/default/opendkim regexp=^SOCKET= line='SOCKET="inet:{{ dkim_milter_port }}@localhost"'
  notify:
   - restart opendkim
  when: ansible_os_family == 'Debian'

- name: opendkim directory present
  file: path=/etc/opendkim state=directory

- name: opendkim keys directory present
  file:
    path: /etc/opendkim/keys
    state: directory
    owner: opendkim
    group: "{{ administrative_group }}"
    mode: 0750

- name: opendkim domain directories present
  file:
    state: directory
    path: "/etc/opendkim/keys/{{ item }}"
    owner: opendkim
    group: "{{ administrative_group }}"
    mode: 0750
  with_items: "{{ dkim_domains }}"

- name: Upload DKIM private key for wildcard signing by '{{ dkim_wildcard_sign_all_with_domain }}'
  copy:
    src: "{{ dkim_path_to_wildcard_key }}"
    dest: "/etc/opendkim/keys/{{ dkim_wildcard_sign_all_with_domain }}/default.private"
    mode: 0400
    owner: opendkim
    group: opendkim
    force: true
    backup: true
  notify:
    - restart postfix
    - restart opendkim
  when: dkim_path_to_wildcard_key | trim() != ''
    and dkim_wildcard_sign_all_with_domain | trim() != ''

- name: opendkim TrustedHosts present
  template: src=TrustedHosts.j2 dest=/etc/opendkim/TrustedHosts
  notify:
   - restart opendkim

- name: opendkim is configured
  template: src=opendkim.conf.j2 dest=/etc/opendkim.conf
  notify:
   - restart opendkim

- name: opendkim KeyTable is configured
  template: src=KeyTable.j2 dest=/etc/opendkim/KeyTable
  notify:
   - restart opendkim

- name: opendkim SigningTable is configured
  template: src=SigningTable.j2 dest=/etc/opendkim/SigningTable
  notify:
   - restart opendkim

- name: generate signing key if not present
  shell: opendkim-genkey -s {{ dkim_selector }} -d {{ item }} -D /etc/opendkim/keys/{{ item }}
  args:
    creates: "/etc/opendkim/keys/{{ item }}/{{ dkim_selector }}.private"
  with_items: "{{ dkim_domains }}"
  notify:
   - restart opendkim

- name: ensure signing key owner
  file: path=/etc/opendkim/keys/{{ item }}/{{ dkim_selector }}.private owner=opendkim group=opendkim
  with_items: "{{ dkim_domains }}"

- name: opendkim is running
  service:
    name: opendkim
    state: started
    enabled: yes
